version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: pablotrone/kittygram_backend
    container_name: kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: pablotrone/kittygram_frontend
    container_name: kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: pablotrone/kittygram_gateway
    container_name: gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
